version: '3.1'
services:
    reverse-proxy:
        image: traefik:v2.2
        command:
            --api.insecure=true
            --providers.docker
            --providers.docker.swarmMode=true
            --entrypoints.web.address=:80
            --entrypoints.websecure.address=:443
            --certificatesresolvers.myresolver.acme.email=info@tech-savvy.io
            --certificatesresolvers.myresolver.acme.storage=acme.json
            --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
        ports:
            - "8080:8080"
            - "80:80"
            - "443:443"
        volumes:
            - "./letsencrypt:/letsencrypt"
            - "/var/run/docker.sock:/var/run/docker.sock"
    dandoenwedat:
        image: apache-php-se-dev:v1.0
        container_name: 'dandoenwedat-web'
        volumes:
            - ../../application/web/DocumentRoot:/var/www/html
            - ../../application/web/devconfig/apache/vhosts:/etc/apache2/sites-enabled
            - ../../application/web/devconfig/php/php.ini:/usr/local/etc/php/php.ini
            - ../../application/web/devconfig/apache/apache2.conf:/etc/apache2/apache2.conf
        env_file:
            - ../../environment/dev/.db.env
            - ../../environment/dev/.s3.env    
        environment:
            - local_ip=127.0.0.1
        deploy:
            labels:
                - traefik.http.routers.web.rule=Host(`localhost`,`dandoenwedat.com`, `www.dandoenwedat.com`)
                - traefik.http.routers.web.tls=true
                - traefik.http.routers.web.tls.certresolver=myresolver
                - traefik.http.services.web-service.loadbalancer.server.port=80
    database:
        image: mysql:5.7.30
        container_name: dandoenwedat-mysql
        restart: 'always'
        ports:
            - "3306:3306"
        volumes: 
            - ../../application/data/mysql:/var/lib/mysql
        env_file:
            - ../../environment/dev/.db.env
            - ../../environment/dev/.s3.env