version: '3.1'
services:
    reverse-proxy:
        image: traefik:v2.2
        command:
            --api.insecure=true
            --providers.docker.swarmMode=true
            --entrypoints.web.address=:80
            --entrypoints.websecure.address=:443
            --providers.file.directory=/configuration
            # --certificatesresolvers.myresolver.acme.email=info@tech-savvy.io
            # --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
            # --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
        ports:
            - "8080:8080"
            - "80:80"
            - "443:443"
        volumes:
            - ./traefik/config:/configuration
            - ./traefik/certs:/etc/traefik/certs
            - /var/run/docker.sock:/var/run/docker.sock
    dandoenwedat:
        image: piepongwong/apache-php-se-dev:v1.11
        container_name: 'dandoenwedat-web'
        volumes:
            - ../../application/web/DocumentRoot:/var/www/html
            - ../../application/web/devconfig/apache/vhosts:/etc/apache2/sites-enabled
            - ../../application/web/devconfig/php/php.ini:/usr/local/etc/php/php.ini
            - ../../application/web/devconfig/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ../../application/web/devconfig/apache/apache2.conf:/etc/apache2/apache2.conf
        env_file:
            - ../../environment/dev/.db.env
            - ../../environment/dev/.s3.env    
            - ../../environment/dev/.smtp.env
        environment:
            - local_ip=127.0.0.1
        deploy:
            labels:
                - traefik.http.routers.web.rule=Host(`localhost`,`dandoenwedat.com`, `www.dandoenwedat.com`)
                - traefik.http.routers.web.tls=true
                - traefik.http.routers.web.tls.certresolver=myresolver
                - traefik.http.services.web-service.loadbalancer.server.port=80
                - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
                - traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)
                - traefik.http.routers.redirs.middlewares=redirect-to-https
    database:
        image: mysql:5.7.30
        container_name: dandoenwedat-mysql
        restart: 'always'
        ports:
            - "3306:3306"
        volumes: 
            - ddwd-dev-database:/var/lib/mysql
        env_file:
            - ../../environment/dev/.db.env
            - ../../environment/dev/.s3.env
volumes:
    ddwd-dev-database:
        external: true