version: '3.1'
services:
    php-apache:
        image: piepongwong/php-apache-se:dev
        build: ./
        container_name: 'dandoenwedat-web'
        ports:
            - 80:80
        links: 
            - database    
        volumes:
            - ./DocumentRoot:/var/www/html
            - ./devconfig/apache/vhosts:/etc/apache2/sites-enabled
            - ./devconfig/php/php.ini:/usr/local/etc/php/php.ini
            - ./devconfig/apache/apache2.conf:/etc/apache2/apache2.conf
            - ./logs/apache2:/var/log/apache2
    database:
        image: mysql:5.7.30
        container_name: dandoenwedat-mysql
        restart: 'always'
        ports:
            - "3306:3306"
        volumes: 
            - ./data/mysql:/var/lib/mysql
            - ./logs/mysql:/var/log/mysql
        environment:
            MYSQL_DATABASE: dandoenwedat
            MYSQL_USER: root
            MYSQL_PASSWORD: /run/secrets/mysql_password
            MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
        secrets:
            - mysql_password
            - mysql_root_password
secrets:
    mysql_root_password:
        file: ./secrets/mysql_root_password.txt
    mysql_password:
        file: ./secrets/mysql_password.txt
    