version: '3.1'
services:
    reverse-proxy:
        image: traefik:v2.2
        command:
            --api.insecure=true
            --providers.docker.swarmMode=true
            --entrypoints.web.address=:80
            --entrypoints.websecure.address=:443
            --entrypoints.web.http.redirections.entryPoint.to=websecure
            --entrypoints.web.http.redirections.entryPoint.scheme=https
            --entrypoints.web.http.redirections.entrypoint.permanent=true
            --certificatesresolvers.myresolver.acme.email=info@tech-savvy.io
            --certificatesresolvers.myresolver.acme.storage=acme.json
            --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
        ports:
            - "8080:8080"
            - "80:80"
            - "443:443"
        volumes:
            - "./letsencrypt:/letsencrypt"
            - "/var/run/docker.sock:/var/run/docker.sock"
    dandoenwedat:
        image: piepongwong/apache-php-se-prod:latest
        volumes:
            - ./DocumentRoot/public:/var/www/html/public
        env_file:
            - ../../environment/dev/.db.env
            - ../../environment/dev/.s3.env
            - ../../environment/dev/.smtp.env
        deploy:
            labels:
                - traefik.http.routers.web.rule=Host(`${local_ip}`,`dandoenwedat.com`, `www.dandoenwedat.com`)
                - traefik.http.routers.web.tls=true
                - traefik.http.routers.web.tls.certresolver=myresolver
                - traefik.http.services.web-service.loadbalancer.server.port=80
    database:
        image: mysql:5.7.30
        container_name: dandoenwedat-mysql
        restart: 'always'
        ports:
            - "3306:3306"
        volumes: 
            - ../../application/data/mysql:/var/lib/mysql
        env_file:
            - ../../environment/dev/.db.env
            - ../../environment/dev/.s3.env
            