version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.15.0-node
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.8
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -f ./docker/prod/dockerfile . --tag piepongwong/apache-php-se-prod:v4.$CIRCLE_BUILD_NUM --tag piepongwong/apache-php-se-prod:latest
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push piepongwong/apache-php-se-prod:latest
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@dandoenwedat.com "sudo su && docker pull piepongwong/apache-php-se-prod:latest
            && docker service update ddwd_dandoenwedat
            && docker image prune"
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy once build job has completed
          filters:
            branches:
              only: production # only deploy on the production branch  