version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15.0-node
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.8
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -f ./docker/prod/dockerfile . --tag piepongwong/apache-php-se-prod:v4.$CIRCLE_BUILD_NUM --tag piepongwong/apache-php-se-prod:latest
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push piepongwong/apache-php-se-prod:latest
