version: '3.1'
services:
    reverse-proxy:
        image: traefik:v2.2
        command:
            --providers.docker.swarmMode=true
            --entrypoints.web.address=:80
            --entrypoints.websecure.address=:443
            --certificatesresolvers.myresolver.acme.email=info@tech-savvy.io
            --certificatesresolvers.myresolver.acme.storage=acme.json
            --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./letsencrypt:/letsencrypt"
            - "/var/run/docker.sock:/var/run/docker.sock"
    dandoenwedat:
        image: piepongwong/apache-php-se-prod:v1.0
        volumes:
            - ./DocumentRoot/public:/var/www/html/public
        env_file:
            - ../../environment/prod/.db.env
            - ../../environment/prod/.s3.env
        deploy:
            labels:
                - traefik.http.routers.web.rule=Host(`${local_ip}`,`dandoenwedat.com`, `www.dandoenwedat.com`)
                - traefik.http.routers.web.tls=true
                - traefik.http.routers.web.tls.certresolver=myresolver
                - traefik.http.services.web-service.loadbalancer.server.port=80
